### ISSUE TITLE
JS8Call  deferred messages 

### ISSUE THREAD

**Issue by UgoPoddine** [jfrancis42/js8net#3]
Hello Jeff, 

thank-you for your valuable job.
Perhaps due to my not fantastic programming capabilities I have missed the point, but is there, in js8net, a function to fill from outside the "Store the message locally" for deferred transmission capability of JS8Call ?
I have seen that the deferred messages are stored in a sqlite database in form of json blob field (for doing stuff more complicated), but before trying to use sqlite library perhaps an API function is already there.
This function is really useful in a “store & forward” scenario.

Any suggestion appreciated
73 IU1IPB Ugo

**Comment by jfrancis42** [comment]
Hi, Ugo. Apologies for the delay, I never saw this original message. Unfortunately, the JS8 API does not support this functionality. I JS8 rewrite (with much better API support) was promised years ago, but has never materialized. I agree that this functionality would be extremely useful, but I have no way to implement it (other than directly manipulating sqlite, as you suggested, which I don't consider a viable option).

**Comment by UgoPoddine** [comment]
HI Jeff,

thank-you for your kind answer.
Your effort is in any case strongly appreciated.
In the future, if you find time, the integration with some kind of DTN
protocol would be a real step ahead in digital HF ham radio.
At the moment I was able to solve the issue reading and storing
DIRECTED.TXT and writing directly on the sqlite database.
Not so clean, but it seems to work.

Thank-you
73 IU1IPB Ugo







Il giorno mar 23 gen 2024 alle ore 21:25 Jeff Francis <
***@***.***> ha scritto:
