### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by DanielVukelich** [jfrancis42/js8net#4]
Would you mind adding a LICENSE file for this project?  I'd like to modify and/redistribute parts to use in a GPL v3 licensed project of my own.

**Comment by jfrancis42** [comment]
Done (actually done about a week ago, but forgot to reply). If you don't mind, drop me a link to your project. Always interested in how people are using this.

**Comment by DanielVukelich** [comment]
Thanks!

My project is a headless Raspberry Pi running JS8Call that you can use for self-spotting POTA/SOTA activations through your phone.  My plan is to use JS8Net.py to send the SOTA/POTA activation messages through a web UI.  Obviously, there are tools like SOTAmat that do this without needing as RasPi, but this is as much an excuse to learn ansible and improve my sysadmin knowledge as anything else.

The web UI is hosted at https://gitlab.com/DanVukelich/pi-spot-interface, and the ansible playbook is https://gitlab.com/DanVukelich/pi-spot
